image: node:8.4.0

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install -g aerobatic-cli gulp-cli
            - npm install
            - gulp build --no-cache --no-notify --throw-errors
            - aero deploy
  custom:
    build:
      - step:
          script:
            - npm install -g aerobatic-cli gulp-cli
            - npm install
            - gulp build --no-cache --no-notify --throw-errors
            - aero deploy
  custom:
    lint:
      - step:
          script:
            - npm install -g gulp-cli
            - npm install
            - gulp lint --no-notify
